CREATE DATABASE IF NOT EXISTS test;
USE test;
DROP TABLE IF EXISTS `EMPLOYEE`;
CREATE TABLE IF NOT EXISTS `EMPLOYEE` (
  `ID` bigint,
  `NAME` string,
  CONSTRAINT `SYS_PK_BUCKETING_COLS` PRIMARY KEY (`ID`) DISABLE
)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\|' ;
--STORED BY 'org.apache.hive.storage.jdbc.JdbcStorageHandler'

LOAD DATA LOCAL INPATH '/tmp/hive/employee.dat'
OVERWRITE INTO TABLE EMPLOYEE;

select * from EMPLOYEE;